Repository unb-mds/2023-2-SuaGradeUnB, pull requests merged in 2023-09, with the labels that each got.

#2 github(issue): definição dos templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/docs-repair.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/rabbit.md
Labels: documentation

#7 github(issue): cria o template para tasks gerais
  .github/ISSUE_TEMPLATE/tasks.md
Labels: documentation

#11 docs(mkdocs): inicializa a primeira versão da documentção
  .github/workflows/docs.yml
  .gitignore
  docs/contributing.md
  docs/index.md
  docs/sprints/sprint-0.md
  docs/sprints/sprint-template.md
  mkdocs.yml
Labels: documentation, ci

#19 docs(mkdocs): relatório dos objetivos da sprint 1
  docs/sprints/sprint-1.md
  mkdocs.yml
Labels: documentation

#23 Feat/api/config
  .gitignore
  api/.env.example
  api/api/__init__.py
  api/api/asgi.py
  api/api/settings.py
  api/api/urls.py
  api/api/wsgi.py
  api/manage.py
  requirements.txt
  scripts/env.sh
Labels: dependencies, devops, task

#24 docker(api): configurar o docker para ambiente dev da API
  api/.env.example
  api/api/admin.py
  api/api/apps.py
  api/api/management/__init__.py
  api/api/management/commands/__init__.py
  api/api/management/commands/initadmin.py
  api/api/migrations/__init__.py
  api/api/models.py
  api/api/tests.py
  api/api/views.py
  api/core/__init__.py
  api/core/asgi.py
  api/core/settings/base.py
  api/core/settings/dev.py
  api/core/settings/prod.py
  api/core/urls.py
  api/core/wsgi.py
  api/manage.py
  docker-compose.yml
  docker/Dockerfile
  docker/entrypoint.sh
  requirements.txt
Labels: dependencies, docker, devops

#26 docs(readme): descreve o projeto e como inicializa
  README.md
Labels: documentation, dependencies

#28 docs(readme): corrige documentação README
  README.md
Labels: documentation
