Repository unb-mds/2023-2-SuaGradeUnB, pull requests merged in 2023-12, with the labels that each got.

#131 devops(deploy): configura o ambiente de deploy para o heroku
  .github/workflows/docs.yml
  .github/workflows/test.yml
  Makefile
  README.md
  api/.env.example
  api/Procfile
  api/api/management/commands/updatedb.py
  api/config/entrypoint.sh
  api/core/settings/base.py
  api/core/settings/dev.py
  api/core/settings/prod.py
  api/requirements.txt
  api/runtime.txt
  docker/Dockerfile
  docs/executing.md
Labels: documentation, dependencies, ci, devops

#135 api(google): Ajusta erro urgente do Google OAuth
  api/users/backends/google.py
Labels: bug, back-end, API

#137 fix(front): arrumar responsividades para telas de início e páginas na aplicação
  web/app/components/AsideButton.tsx
  web/app/components/AsideSchedulePopUp/AsideSchedulePopUp.tsx
  web/app/components/AsideSchedulePopUp/Form/DisciplineOptionForm.tsx
  web/app/components/AsideSchedulePopUp/Form/InputForm.tsx
  web/app/components/AsideSchedulePopUp/Tooltip.tsx
  web/app/components/AsideSchedulePopUp/types/types.ts
  web/app/components/ClassInfo.tsx
  web/app/components/InfoHeader.tsx
  web/app/components/LogoImageHandler.tsx
  web/app/components/SignInSection.tsx
  web/app/contexts/YearPeriodContext.tsx
  web/app/favicon.ico
  web/app/hooks/useWindowDimensions.ts
  web/app/layout.tsx
  web/app/page.tsx
  web/app/schedules/home/components/AddDisciplineButton.tsx
  web/app/schedules/home/components/GenerateScheduleButton.tsx
  web/app/schedules/home/page.tsx
  web/app/schedules/layout.tsx
  web/app/schedules/profile/page.tsx
  web/package-lock.json
  web/package.json
  web/public/google.jpg
  web/public/google.svg
  web/public/icons/home.jpg
  web/public/icons/logotipo.jpg
  web/public/icons/profile.jpg
  web/public/icons/schedule.jpg
  web/public/logo.png
  web/public/logo.svg
  web/public/next.svg
  web/public/vercel.svg
  web/tailwind.config.ts
Labels: bug, front-end

#140 frontend(info): criação da tela de informações para novos usuários
  web/app/globals.css
  web/app/schedules/info/page.tsx
  web/app/schedules/layout.tsx
  web/next.config.js
  web/public/icons/info.jpg
Labels: task, front-end

#138 task(schedule): Cria o algoritmo de geração de matérias
  api/api/serializers.py
  api/api/tests/test_schedule_api.py
  api/api/urls.py
  api/api/views.py
  api/utils/db_handler.py
  api/utils/schedule_generator.py
  api/utils/tests/test_database_handler.py
  api/utils/tests/test_schedule_generator.py
Labels: back-end, API

#141 docs(fix-page-como-executar): corrigindo texto da página como executar
  docs/executing.md
Labels: documentation

#144 task(schedule/save): criar a rota de salvamento de grade p/usuários autênticados
  api/api/admin.py
  api/api/migrations/0007_schedule.py
  api/api/models.py
  api/api/serializers.py
  api/api/tests/test_error_request_body_schedule_save.py
  api/api/tests/test_schedule_models.py
  api/api/tests/test_schedule_save.py
  api/api/tests/test_search_api.py
  api/api/urls.py
  api/api/views/save_schedule.py
  api/api/views/utils.py
  api/api/views/views.py
  api/core/settings/base.py
  api/setup.cfg
  api/users/views.py
  api/utils/db_handler.py
  api/utils/json_pretty.py
Labels: task, back-end

#149 task(get-schedule): Cria API para obtenção de grades do usuário
  api/api/migrations/0008_schedule_created_at.py
  api/api/models.py
  api/api/serializers.py
  api/api/tests/test_get_schedules_api.py
  api/api/tests/test_schedule_save.py
  api/api/urls.py
  api/api/views/get_schedules.py
  api/utils/db_handler.py
Labels: back-end, API

#152 task(frontend): trás as modificações da api para salvamento de grade para continuidade da criação do flow layout
  api/api/admin.py
  api/api/migrations/0007_schedule.py
  api/api/migrations/0008_schedule_created_at.py
  api/api/models.py
  api/api/serializers.py
  api/api/tests/test_error_request_body_schedule_save.py
  api/api/tests/test_get_schedules_api.py
  api/api/tests/test_schedule_models.py
  api/api/tests/test_schedule_save.py
  api/api/tests/test_search_api.py
  api/api/urls.py
  api/api/views/get_schedules.py
  api/api/views/save_schedule.py
  api/api/views/utils.py
  api/api/views/views.py
  api/core/settings/base.py
  api/setup.cfg
  api/users/views.py
  api/utils/db_handler.py
  api/utils/json_pretty.py
  web/app/components/AsideSchedulePopUp/Form/InputForm.tsx
  web/app/schedules/info/page.tsx
  web/app/schedules/layout.tsx
  web/public/icons/google.jpg
  web/public/icons/search.jpg
Labels: feature request, API

#158 fix(api): agora a api pode salvar grades com datas especias
  api/api/tests/test_get_schedules_api.py
  api/api/tests/test_schedule_delete.py
  api/api/tests/test_schedule_save.py
  api/api/views/delete_schedule.py
  api/api/views/save_schedule.py
  api/api/views/schedules.py
  api/utils/db_handler.py
  api/utils/tests/test_database_handler.py
  api/utils/tests/test_schedule_generator.py
Labels: bug, back-end

#157 task(front): cria página de criação de grades com funcionalidades propostas
  api/api/views/get_schedules.py
  api/utils/db_handler.py
  web/app/components/AsideSchedulePopUp/DisciplineFragment.tsx
  web/app/components/AsideSchedulePopUp/Tooltip.tsx
  web/app/components/ClassInfo.tsx
  web/app/components/InfoHeader.tsx
  web/app/components/Modal/Modal.tsx
  web/app/components/Schedule/Schedule.tsx
  web/app/components/SchedulePreview/SchedulePreview.tsx
  web/app/contexts/SchedulesContext.tsx
  web/app/contexts/UserContext.tsx
  web/app/globals.css
  web/app/hooks/useSchedules.ts
  web/app/layout.tsx
  web/app/schedules/home/components/GenerateScheduleButton.tsx
  web/app/schedules/info/page.tsx
  web/app/schedules/layout.tsx
  web/app/schedules/mygrades/page.tsx
  web/app/schedules/profile/page.tsx
  web/app/utils/api/deleteSchedule.ts
  web/app/utils/api/generateSchedule.ts
  web/app/utils/api/getSchedules.ts
  web/app/utils/api/saveSchedule.ts
  web/app/utils/dates.ts
  web/app/utils/settingsWithAuth.ts
  web/package-lock.json
  web/package.json
  web/public/icons/delete.jpg
  web/public/icons/download.jpg
  web/public/icons/expand_less.png
  web/public/icons/expand_more.png
  web/public/icons/upload.jpg
  web/tailwind.config.ts
  web/tsconfig.json
Labels: task, front-end

#164 docs(README): adiciona seção de atualização do banco de dados
  README.md
Labels: documentation, task

#163 docs(mkdocs): adiciona documentação da arquitetura do projeto
  docs/api.md
  docs/architecture.md
  docs/frontend/finalização.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#162 docs(conduct): adiciona código de conduta padrão
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#165 devops(ci): faz deploy da documentação apenas quando há mudança na pasta
  .github/workflows/docs.yml
Labels: documentation, ci, devops

#166 task(front): arrumando erros de responsividade do site
  web/app/components/AsideSchedulePopUp/ClassInfoBox.tsx
  web/app/components/AsideSchedulePopUp/Form/DisciplineOptionForm.tsx
  web/app/components/AsideSchedulePopUp/Tooltip.tsx
  web/app/components/ClassInfo.tsx
  web/app/components/InfoHeader.tsx
  web/app/components/SchedulePreview/SchedulePreview.tsx
  web/app/layout.tsx
  web/app/schedules/home/components/AddDisciplineButton.tsx
  web/app/schedules/home/components/GenerateScheduleButton.tsx
  web/app/schedules/info/page.tsx
  web/app/schedules/layout.tsx
  web/app/schedules/mygrades/page.tsx
  web/app/schedules/profile/page.tsx
  web/app/styles/tooltip.module.css
  web/public/icons/add.jpg
  web/public/icons/question.jpg
Labels: bug, task, front-end

#168 fix(popup): arruma do popup com muitas disciplinas
  web/app/components/AsideSchedulePopUp/AsideSchedulePopUp.tsx
Labels: bug, front-end

#170 fix(front): quando o usuário faz logout e tem grades no cloud essas não ficam mais no buffer
  web/app/page.tsx
  web/app/schedules/layout.tsx
  web/app/schedules/profile/page.tsx
  web/app/utils/api/logout.ts
Labels: bug, front-end

#172 mkdocs(docs): Adiciona as sprints 12 e 13
  docs/sprints/sprint-12.md
  docs/sprints/sprint-13.md
  mkdocs.yml
Labels: documentation

#173 fix(docs): muda o link do repositório em todos os locais do código após mudar o nome no github
  README.md
  api/core/urls.py
  docs/contributing.md
  docs/executing.md
  docs/sprints/sprint-5.md
  mkdocs.yml
  web/app/schedules/info/page.tsx
Labels: bug, documentation, task

#177 dependencies/security/update: django 4.2.5 to 4.2.7 - urlib3 2.0.5 to 2.0.7 - cryptography 41.0.4 to 41.0.6
  api/requirements.txt
Labels: dependencies, security

#167 api(search): Filtra busca por nome do professor
  api/api/serializers.py
  api/api/tests/test_search_api.py
  api/api/views/views.py
  api/utils/db_handler.py
Labels: feature request, back-end, API

#181 api(views): improve error handling security
  api/api/views/views.py
Labels: back-end, API

#182 front(schedules): adiciona secção de preferência antes da geração de grades e frame de loading
  web/app/schedules/home/components/GenerateScheduleButton.tsx
  web/app/schedules/layout.tsx
  web/app/utils/api/generateSchedule.ts
Labels: task, front-end, API

#183 task(api): otimiza piores e médios casos da atualização do db por meio de redis cache, pages fingerprints e multithreading
  api/.env.example
  api/api/decorators.py
  api/api/management/commands/updatedb.py
  api/api/models.py
  api/api/tests/test_models.py
  api/core/settings/base.py
  api/requirements.txt
  api/utils/db_handler.py
  api/utils/functions.py
  api/utils/management/commands/updatemock.py
  api/utils/tests/test_web_scraping.py
  api/utils/web_scraping.py
  docker-compose.yml
Labels: task, back-end
