Repository unb-mds/2023-2-SuaGradeUnB, pull requests merged in 2023-10, with the labels that each got.

#31 docs(sprint): relatório de descrição da sprint 2
  docs/sprints/sprint-2.md
  mkdocs.yml
Labels: documentation

#34 devops(google-auth): adiciona dependências necessárias
  requirements.txt
Labels: dependencies, devops

#39 python(req): bs4 lib adicionada para scraping
  requirements.txt
Labels: dependencies, docker, devops

#43 bug(sprint): ajusta o número da sprint na docs
  docs/sprints/sprint-3.md
Labels: documentation

#41 Task/web scraping
  .gitignore
  api/api/utils/sessions.py
  api/api/utils/web_scraping.py
Labels: task, back-end

#45 docker(front-end): cria o ambiente de desenvolvimento front-end.
  docker-compose.yml
  docker/Dockerfile.web
  web/.eslintrc.json
  web/.gitignore
  web/README.md
  web/app/favicon.ico
  web/app/globals.css
  web/app/layout.tsx
  web/app/page.module.css
  web/app/page.tsx
  web/next.config.js
  web/package.json
  web/public/next.svg
  web/public/vercel.svg
  web/tsconfig.json
Labels: docker, devops

#47 oauth(jwt): definição do fluxo de autênticação social com oauth2
  api/.env.example
  api/api/management/commands/initadmin.py
  api/core/settings/base.py
  api/core/urls.py
  api/users/__init__.py
  api/users/admin.py
  api/users/apps.py
  api/users/backends/google.py
  api/users/backends/utils.py
  api/users/migrations/0001_initial.py
  api/users/migrations/__init__.py
  api/users/models.py
  api/users/simplejwt/decorators.py
  api/users/simplejwt/serializers.py
  api/users/tests.py
  api/users/urls.py
  api/users/views.py
  requirements.txt
Labels: dependencies, task, back-end

#50 git(ignore): readiciona o gitignore para o django files
  .gitignore
  scripts/env.sh
Labels: documentation, dependencies, devops

#53 docs(README): atualiza parte de documentação
  README.md
Labels: documentation

#48 (task): "Definição de Rotas da API"
  docs/api.md
  mkdocs.yml
Labels: documentation, task, back-end

#55 docs(mkdocs): criação da documentação da sprint 4
  docs/sprints/sprint-4.md
  mkdocs.yml
Labels: documentation

#56 Docs/frontend
  docs/frontend/semana-0.md
  docs/frontend/semana-1.md
  docs/frontend/semana-2.md
  docs/frontend/semana-3.md
  docs/frontend/semana-4.md
  docs/frontend/semana-5.md
  docs/frontend/semana-6.md
  mkdocs.yml
Labels: documentation, front-end

#57 docs(mkdocs): adicona documentação da sprint 4
  docs/sprints/sprint-4.md
  docs/sprints/sprint-5.md
  mkdocs.yml
Labels: documentation, task

#59 docs(mkdocs): nova arquitetura definida na sprint 3
  docs/sprints/sprint-3.md
Labels: documentation, task, sprint
