Repository unb-mds/2023-2-SuaGradeUnB, pull requests merged in 2024-01, with the labels that each got.

#186 fix(api): arruma função de ano/período atual que tinha incosistência nos dias 30/31 de dez
  api/utils/sessions.py
  api/utils/tests/test_date_utils.py
Labels: bug, task, back-end

#193 front(ux): melhora perfomance de carregamento de ícones com jpg
  web/app/components/AsideSchedulePopUp/ClassInfoBox.tsx
  web/app/components/AsideSchedulePopUp/Tooltip.tsx
  web/app/components/DisciplineBox.tsx
  web/app/components/Modal/Modal.tsx
  web/public/icons/close.jpg
  web/public/icons/remove.jpg
Labels: task, front-end

#191 Adiciona template de pull request para contribuição.
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#196 Corrige erro de localização do PR template
  .github/pull_request_template.md
Labels: documentation

#194 ux(schedule-generator): adiciona mensagem descritiva de conflito de grade horária
  api/api/serializers.py
  api/api/tests/test_generate_schedule_api.py
  api/api/tests/test_get_schedules_api.py
  api/api/tests/test_schedule_delete.py
  api/api/views/save_schedule.py
  api/api/views/views.py
  api/utils/schedule_generator.py
  api/utils/tests/test_schedule_generator.py
  web/app/contexts/SchedulesContext.tsx
  web/app/schedules/home/components/GenerateScheduleButton.tsx
  web/app/utils/errorToast.ts
Labels: task, back-end, front-end, API

#195 front(ux): travar seleção de período
  web/app/components/AsideSchedulePopUp/AsideSchedulePopUp.tsx
  web/app/components/AsideSchedulePopUp/Form/DisciplineOptionForm.tsx
Labels: task, front-end, UI/UX
